# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md
- screenshot.png
- LICENSE.md
- alembic-jekyll-theme.gemspec
- .git/
- .directory
- .gitignore
- jekyll.sh
- blog/gen-thumbs.sh
- blog/add-copyright.sh
- DeployedWebsiteHTML
- .jekyll-cache

include:
- search.md
- categories.md

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 20 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://github.com # jekyll-mentions > service used when @replying
github:
  username: marcocipriani01 # jekyll-seo-tag > Owners github username
author: marcocipriani01 # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Marco Cipriani # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/marcocipriani01
    - https://www.instagram.com/marco.cipriani.01/
    - https://www.youtube.com/channel/UCXxWdFx540ZKEMsCauxPuAg
    - https://github.com/marcocipriani01
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: /:year/:month/:day/:title:output_ext  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Rome # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Astrophotos & more # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text: >-
      ## <span style="color:white">Blog</span>

      <span style="color:white">My astronomy pictures, projects, suggestions,
      tips and tricks.</span>
    feature_image: "assets/cover.jpg"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/cover.jpg" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Marco Cipriani" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.png" # Site logo, also used in jekyll-seo-tag
# Site description and default description, also used in jekyll-seo-tag
description: >-
  I’m a young astronomy enthusiast, attending the high school somewhere in Italy.
  In my free time, I take photos of the universe with my telescope and I often write some programs,
  utilities or Android applications to simplify its use. In my website I describe my projects
  and publish my photos of the universe.
url: "https://marcocipriani01.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/marcocipriani01/marcocipriani01.github.io"
email: "marco.cipriani.01@gmail.com"
disqus: "marcocipriani01" # Blog post comments, uncomment the option and set the site ID from your Disqus account
google_analytics: 'UA-132870782-1'
# google_analytics_anonymize_ip: ''
cookie_consent: true
cookie_policy: "https://marcocipriani01.github.io/about#privacy"
cookie_message: "This website uses Google Analytics to ensure users get the best experience on my website"
bing_webmaster: 'BFB5A8B78496AA210C1026F095352AB5'
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: Buy something I made!
  url: /shop
- title: My projects
  url: /projects
- title: Astro-blog
  url: /blog/
#- title: Categories
#  url: /categories.html
- title: Search
  url: /search.html
- title: About
  url: /about.html

navigation_footer:
- title: Alembic Jekyll theme by David Darnes
  url: 'https://darn.es'

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  YouTube: 'https://www.youtube.com/channel/UCXxWdFx540ZKEMsCauxPuAg'
  GitHub: 'https://github.com/marcocipriani01'
  Facebook: 'https://www.facebook.com/marcocipriani01'
  Instagram: 'https://www.instagram.com/marco.cipriani.01/'
  link: 'https://marcocipriani01.github.io'
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Facebook: "#3B5998"
  #YouTube: "#FF0000"
  #Instagram: "#bc2a8d"
  Twitter: "#0d94e7"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: "#004D40"
