# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- screenshot.png
- LICENSE.md
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- vendor/cache
- .git/
- .directory
- .gitignore
- jekyll.sh

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 20 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://github.com # jekyll-mentions > service used when @replying
twitter:
  username: marcocipriani01 # jekyll-seo-tag > Owners github username
author: marcocipriani01 # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Marco Cipriani # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
#    - https://twitter.com/DavidDarnes
#    - https://www.facebook.com/daviddarnes
#    - https://www.linkedin.com/in/daviddarnes
    - https://www.youtube.com/channel/UCXxWdFx540ZKEMsCauxPuAg
    - https://plus.google.com/111185483796676656441
    - https://github.com/marcocipriani01

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Rome # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Stuff # Needed for Siteleaf
    output: true
    description: "" # The post list page content
    feature_text: >-
      ## <span style="color:white">Blog</span>

      <span style="color:white">My astronomy pictures, projects, suggestions,
      tips and tricks.</span>
    feature_image: "assets/cover.png"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/cover.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Marco Cipriani" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.png" # Site logo, also used in jekyll-seo-tag
# Site description and default description, also used in jekyll-seo-tag
description: >-
  Marco Cipriani's website. As an astronomy enthusiast, I write programs to
  simplify the use of my telescope or for school projects. I also made some
  Arduino projects.
url: "https://marcocipriani01.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/marcocipriani01/marcocipriani01.github.io"
# email: "me@daviddarnes.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "/assets/logo.png" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site navigation
navigation_header:
  Home: /
  Projects: /projects/index
  OpenFocuser: /projects/OpenFocuser
  Blog: /blog/
  Categories: /categories/
  Search: /search/
  About: /about

navigation_footer:
  Alembic Jekyll theme by David Darnes: 'https://darn.es'

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  YouTube: 'https://www.youtube.com/channel/UCXxWdFx540ZKEMsCauxPuAg'
  Google+: 'https://plus.google.com/111185483796676656441'
  GitHub: 'https://github.com/marcocipriani01'
  link: 'https://marcocipriani01.github.io'
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  # Twitter: "#0d94e7"
  # facebook: "#3B5998"
  Google+: "#DC4E41"
  GitHub: "#000000"
  YouTube: "#FF0000"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
